## Warning this file contains very sensitive data. Ensure the this file is listed in your .gitignore file to prevent potential exposure

[keys]
# CircleCI 
circleci_org_slug = "YOUR_CIRCLECI_ORG_SLUG" # Akin to github/your_user_name
circleci_org_id = "YOUR_CIRCLECI_ORG_ID" # The ID of your org - get it in org settings
circleci_token = "YOUR_CIRCLECI_TOKEN" # Generate in CircleCI account settings

# Third party - Add your other integrations credentials here and update the provisioning.py with resepctive functionality
snyk_token = "YOUR_SNYK_TOKEN"
AWS_ACCESS_KEY_ID = "Your AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "Your AWS Secret Access Keys"
tf_cloud_org_email = "YOUR_TERRAFORM_ACCOUNT_EMAIL_ADDRESS"
tf_cloud_token = "YOUR_TERRAFORM_CLOUD_TOKEN"

# The names of the TF assets you wamt to create
tf_cloud_org_name = "your_tf_org_name"
tf_cloud_workspace = "your_tf_workspace_name"