version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.1
  ggshield: gitguardian/ggshield@1.1.4
  serverless-framework: circleci/serverless-framework@2.0.1
  snyk: snyk/snyk@2.0.1

workflows:
  build_and_deploy:
    jobs:
      - ggshield/scan:
          name: Scanning for Secrets with GitGuardian
          revision: $CIRCLE_SHA1
          context:
            - IDT
      - static_analysis:
          name: Static Code Analysis via Snyk
          context:
            - IDT
          requires:
            - "Scanning for Secrets with GitGuardian"
      - test:
          name: Run PyTest against Application
      - build:
          name: build
          requires:
            - "Run PyTest against Application"
      - deploy:
          name: deploy
          context:
            - AWS
          requires:
            - build

jobs:
  build:
    docker:
      - image: cimg/python:3.9.16-node
    steps:
      - checkout 
      - run:
          name: Install Deps
          command: |
            ls -lah
            pip install -r requirements.txt

  static_analysis:
    docker:
      - image: cimg/python:3.9.16-node
    working_directory: ~/project/python/powertools-sls/
    steps:
      - checkout 
      - run:
          name: Install Deps to be Scanned
          command: |
            ls -lah
            pip install -r requirements.txt
      - snyk/scan:
          severity-threshold: critical
  test:
    docker:
      - image: cimg/python:3.9.16-node
    working_directory: ~/project/python/powertools-sls/
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            ls -lah
            pip install -r requirements.txt
            pytest
  deploy:
    executor: serverless-framework/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless-framework/setup
      - run:
          name: Deploy to AWS Lambda
          command: serverless deploy -v
