service: hello-python-powertools-sls

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  architecture: arm64

  logs:
    httpApi: true

  tracing:
    lambda: true
    apiGateway: true

functions:
  hello:
    handler: src/handler.lambda_handler
    layers:
      - arn:aws:lambda:${aws:region}:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:31
    events:
      - httpApi: '*'


resources:
  Resources:
    inventoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: inventory
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
